name: My Assignment Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: pip install flask pytest && pytest
      - name: Build Docker
        run: docker build -t my-app .
